name: Deployment Exercise 1
on: push
jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
           - name: get code
             uses: actions/checkout@v4
           - name: Install Dependencies
             uses: npm ci
           - name: Lint
             uses: npm run lint
           - name: Test Code
             uses: npm run test
           - name: Build code
             uses: npm run build
           - name: Deploy code
             uses: echo "Deploying..."